---
# The main playbook to install Ceres Fair Food on a server

- hosts: all

  roles:
    - role: admin-users
      become: yes

    - role: config

    - role: fairfood-dependencies
      become: yes

    - role: app-user
      tags: app-user

    - role: rbenv

    - role: mail
      become: yes

    - role: sunfoxcz.dkim
      become: yes

    - role: mysql
      become: yes

    - role: puma
      become: yes
      tags: puma

    - role: certbot
      become: yes
      when: https |bool

    - role: jdauphant.nginx
      vars:
        nginx_sites:
          fairfood: "{{ nginx_sites_available.fairfood_http }}"
      become: yes
      when: not https
      tags: nginx

    - role: jdauphant.nginx
      vars:
        nginx_sites:
          default: "{{ nginx_sites_available.default }}"
          fairfood_http: "{{ nginx_sites_available.fairfood_http_to_https_redirect }}"
          fairfood_https: "{{ nginx_sites_available.fairfood_https }}"
      become: yes
      when: https |bool
      tags: nginx

    - role: nginx
      become: yes
      tags: nginx

    - role: fairfood
      become: yes
      become_user: "{{ app_user }}"
      tags: fairfood
