---
# The main playbook to install Ceres Fair Food on a server

- hosts: all

  roles:
    - role: app-user

    - role: rbenv
      ruby_version: 1.9.3-p551

    - role: mysql
      become: yes

    - role: unicorn
      become: yes

    - role: jdauphant.nginx
      vars:
        nginx_sites:
          fairfood: "{{ nginx_sites_available.fairfood_http }}"
      become: yes
      when: not https

    - role: jdauphant.nginx
      vars:
        nginx_sites:
          #default: "{{ nginx_sites_available.default }}"
          fairfood_http: "{{ nginx_sites_available.fairfood_http_to_https_redirect }}"
          fairfood_https: "{{ nginx_sites_available.fairfood_https }}"
      become: yes
      when: https

    - role: thefinn93.letsencrypt
      become: yes
      letsencrypt_email: "{{ developer_email }}"
      letsencrypt_cert_domains:
        - "{{ domain }}"
      letsencrypt_renewal_command_args: '--renew-hook "systemctl restart nginx"'
      when: https

    - role: fairfood-dependencies
      become: yes

    - role: fairfood
      become: yes
      become_user: "{{ app_user }}"
