---
# The main playbook to install Ceres Fair Food on a server.
# Warning, this will overwrite any manual changes to config on the server.

- hosts: all

  roles:
    - role: admin-users
      tags: admin-users
      become: yes

    - role: config
      tags: config
      become: yes

    - role: fairfood-dependencies
      tags: fairfood-dependencies
      become: yes

    - role: app-user
      tags: app-user

    - role: rbenv
      tags: rbenv

    - role: mail
      tags: mail
      become: yes

    - role: sunfoxcz.dkim
      tags: dkim
      become: yes

    - role: mysql
      tags: mysql
      become: yes

    - role: certbot
      tags: certbot
      become: yes
      when: https |bool

    - role: geolimit
      tags: geolimit
      become: yes

    - role: jdauphant.nginx
      tags: nginx
      vars:
        nginx_sites:
          fairfood: "{{ nginx_sites_available.fairfood_http }}"
      become: yes
      when: not https

    - role: jdauphant.nginx
      tags: nginx
      vars:
        nginx_sites:
          default: "{{ nginx_sites_available.default }}"
          fairfood_http: "{{ nginx_sites_available.fairfood_http_to_https_redirect }}"
          fairfood_https: "{{ nginx_sites_available.fairfood_https }}"
      become: yes
      when: https |bool

    - role: nginx
      tags: nginx
      become: yes

    - role: fairfood
      tags: fairfood
      become: yes
      become_user: "{{ app_user }}"

    - role: puma
      tags: puma
      become: yes
