---

- name: Set timezone for cron jobs using local time
  timezone:
    name: Australia/Melbourne

- name: Remove conflicting system dependencies of the fairfood application
  apt:
    pkg:
    - apache2
    - apache2-bin
    - apache2-utils
    - libapache2-mod-php
    state: "absent"
  become: yes

- name: Install Ansible dependencies
  apt:
    pkg: "acl"
    state: "present"
  become: yes

- name: Install system dependencies of the fairfood application
  apt:
    pkg:
    - git
    - imagemagick
    - memcached
    - monit
    - nginx
    # For Ruby 3.2
    - libyaml-dev
    # For the mysql2 gem
    - libmariadb-dev
    # For mimemagic / paperclip
    - shared-mime-info
    state: "present"
  become: yes

- name: Install monit configuration file
  template:
    src: "monit/rails-fairfood.j2"
    dest: "/etc/monit/conf.d/rails-fairfood"
    mode: 0644

- name: Enable monit httpd interface
  replace:
    path: /etc/monit/monitrc
    # Uncomment matching lines
    regexp: '^#\s?(\s*){{ item }}(.+)$'
    replace: '\1{{ item }}\2'
  loop:
    - 'set httpd port'
    - 'use address localhost'
    - 'allow localhost'
  notify: Reload monit
