---

- name: Set timezone for cron jobs using local time
  timezone:
    name: Australia/Melbourne

- name: Remove conflicting system dependencies of the fairfood application
  apt:
    pkg:
    - apache2
    - apache2-bin
    - apache2-utils
    - libapache2-mod-php
    state: "absent"
  become: yes

- name: Install Ansible dependencies
  apt:
    pkg: "acl"
    state: "present"
  become: yes

- name: Install system dependencies of the fairfood application
  apt:
    pkg:
    - git
    - imagemagick
    - memcached
    - nginx
    # For the mysql2 gem
    - libmariadb-dev
    state: "present"
  become: yes
