---
# Install puma app service

- name: Install puma service
  template:
    src: "puma.service.j2"
    dest: "{{ app_user_home }}/.config/systemd/user/puma.service"

- name: Enable puma at boot
  shell: systemctl --user --machine={{ app_user }}@.host enable puma.service
  args:
    creates: "{{ app_user_home }}/.config/systemd/user/default.target.wants/puma.service"
  become: true
