---
# Mail setup
# Execute this role as root

- name: install mail packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - mailutils

- name: configure receiving locally only
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^inet_interfaces"
    line: "inet_interfaces = loopback-only"
    state: present
  notify: Reload postfix

- name: deactiveate tls for receiving locally
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^smtpd_use_tls"
    line: "smtpd_use_tls=no"
    state: present
  notify: Reload postfix
