---
# Mail setup
# Execute this role as root

- name: install mail packages
  apt:
    pkg:
    - mailutils
    - postfix
    state: present

- name: configure receiving locally only
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^inet_interfaces"
    line: "inet_interfaces = loopback-only"
    state: present
  notify: Reload postfix
