---
# Mail setup
# Execute this role as root

- name: install mail packages
  apt:
    pkg:
    - mailutils
    - postfix
    - pflogsumm
    state: present

- name: configure receiving locally only
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^inet_interfaces"
    line: "inet_interfaces = loopback-only"
    state: present
  notify: Reload postfix

- name: Forward system messages to IT email address
  lineinfile:
    create: yes
    dest: ~/.forward
    regexp: "root"
    line: "{{ email_it }}, /root/mailbox"
    state: present

# Check for email delivery errors and email details to admins
- name: Install pflogsumm-notice script
  template:
    src: "pflogsumm-notice.sh"
    dest: "/root/pflogsumm-notice.sh"
    mode: 0751

- name: Cron job to check postfix log summary at 1am each day
  cron:
    name: "pflogsumm-notice"
    minute: "1"
    hour: "1"
    job: "/root/pflogsumm-notice.sh"