---
# Install rbenv and the need ruby version

- name: install build depends
  apt:
    pkg:
    - build-essential
    - git
    - libcurl4-openssl-dev
    - libffi-dev
    - libreadline-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - zlib1g-dev
    state: present
  become: yes

- name: checkout rbenv repo
  git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "~/.rbenv"
    version: "v1.1.1"
    accept_hostkey: yes
    force: yes
  become: yes
  become_user: "{{ app_user }}"

- name: create plugins directory
  file: state=directory path="~/.rbenv/plugins"
  become: yes
  become_user: "{{ app_user }}"

- name: install plugins for selected users
  git:
    repo: "https://github.com/rbenv/ruby-build.git"
    dest: "~/.rbenv//plugins/ruby-build"
    version: "master"
    accept_hostkey: yes
    force: yes
  become: yes
  become_user: "{{ app_user }}"

- name: add rbenv path to profile
  lineinfile:
    dest: "~/.bash_profile"
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    state: present
    create: yes
  become: yes
  become_user: "{{ app_user }}"

- name: add rbenv initialisation
  lineinfile:
    dest: "~/.bash_profile"
    line: 'eval "$(rbenv init -)"'
    state: present
    create: yes
  become: yes
  become_user: "{{ app_user }}"

- name: install ruby
  command: bash -lc "rbenv install --skip-existing {{ ruby_version }}"
  args:
    creates: "~/.rbenv/versions/{{ ruby_version }}"
  become: yes
  become_user: "{{ app_user }}"

- name: Install bundler
  # This needs to be run inside a bash shell to initialise rbenv
  # See http://stackoverflow.com/questions/22115936/install-bundler-gem-using-ansible
  command: bash -lc "RBENV_VERSION='{{ ruby_version }}' gem install bundler --no-ri --no-rdoc"
  become: yes
  become_user: "{{ app_user }}"
  args:
    creates: "~/.rbenv/shims/bundler"
