---
# Install rbenv and the need ruby version

- name: install build depends
  apt: pkg={{ item }} state=present install_recommends=no
  with_items:
  - build-essential
  - git
  - libcurl4-openssl-dev
  - libffi-dev
  - libreadline-dev
  - libssl1.0-dev
  - libxml2-dev
  - libxslt1-dev
  - libyaml-dev
  - zlib1g-dev
  become: yes

- name: checkout rbenv repo
  git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "~/.rbenv"
    version: "v1.1.1"
    accept_hostkey: yes
    force: yes
  become: yes
  become_user: "{{ app_user }}"

- name: create plugins directory
  file: state=directory path="~/.rbenv/plugins"
  become: yes
  become_user: "{{ app_user }}"

- name: install plugins for selected users
  git: >
    repo="https://github.com/rbenv/ruby-build.git"
    dest="~/.rbenv//plugins/ruby-build"
    version=v20171226
    accept_hostkey=yes
    force=yes
  become: yes
  become_user: "{{ app_user }}"

- name: add rbenv path to profile
  lineinfile:
    dest: "~/.bash_profile"
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    state: present
    create: yes
  become: yes
  become_user: "{{ app_user }}"

- name: add rbenv initialisation
  lineinfile:
    dest: "~/.bash_profile"
    line: 'eval "$(rbenv init -)"'
    state: present
    create: yes
  become: yes
  become_user: "{{ app_user }}"

- name: install ruby
  shell: bash -lc "rbenv install --skip-existing --patch {{ ruby_version }}"
  args:
    stdin: "{{ lookup('file', 'ruby-debian-openssl.patch') }}"
    creates: "~/.rbenv/versions/{{ ruby_version }}"
  become: yes
  become_user: "{{ app_user }}"
