---
# Create the unpriviledged user to run the rails application

- name: Create unprivileged app user
  user:
    name: "{{ app_user }}"
    state: present
    home: "{{ app_user_home }}"
    shell: /bin/bash
    # Set password hash to `*` instead of `!` to enable SSH logins via public key.
    password: "*"
    update_password: on_create

- name: Create sudoers configuration for app user
  become: true
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/{{ app_user }}"
    mode: 0440

# This only works with a root login. Switching via sudo doesn't allow access.
- name: Allow user to run services without login
  shell: loginctl enable-linger {{ app_user }}
  args:
    creates: "/var/lib/systemd/linger/{{ app_user }}"
